import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push('PAGE: '+e.message));
page.on('console',m=>{if(m.type()==='error')errors.push('CONSOLE: '+m.text())});
await page.goto('https://sinhtranthi28286-lang.github.io/trung-tam-ai-thu-lam/?smoke=831',{waitUntil:'domcontentloaded',timeout:45000});
await page.waitForTimeout(6000);
const result=await page.evaluate(async()=>{
 const out={version:document.querySelector('meta[name="thu-lam-version"]')?.content||'',checks:[]};
 const check=async(name,fn)=>{try{await fn();out.checks.push([name,'PASS'])}catch(e){out.checks.push([name,'FAIL',String(e?.message||e)])}};
 document.querySelectorAll('[id*="login" i],[class*="login" i]').forEach(el=>{try{if(getComputedStyle(el).position==='fixed')el.style.display='none'}catch(e){}});
 await check('render overview',()=>{if(typeof renderTTOverview!=='function')throw Error('missing renderTTOverview');renderTTOverview()});
 await check('render staff',()=>{if(typeof renderTTStaff!=='function')throw Error('missing renderTTStaff');renderTTStaff()});
 await check('render work',()=>{if(typeof renderWork!=='function')throw Error('missing renderWork');renderWork()});
 await check('render salary',()=>{if(typeof renderSalary2!=='function')throw Error('missing renderSalary2');renderSalary2()});
 await check('document lookup',()=>{if(typeof renderDocumentLookup!=='function')throw Error('missing renderDocumentLookup');renderDocumentLookup()});
 await check('weekly report page',()=>{if(typeof showCenterPage!=='function')throw Error('missing showCenterPage');showCenterPage('sheet')});
 await check('monthly report page',()=>showCenterPage('monthreport'));
 await check('monthly reload handler exists',()=>{if(typeof reloadMonthlySheet!=='function')throw Error('missing')});
 await check('monthly open handler exists',()=>{if(typeof openMonthlySheet!=='function')throw Error('missing')});
 await check('work modal',()=>{if(typeof openCtrl!=='function')throw Error('missing openCtrl');openCtrl('work')});
 await check('salary modal',()=>openCtrl('salary'));
 await check('directive modal',()=>openCtrl('directives'));
 await check('meeting modal',()=>openCtrl('meeting'));
 return out;
});
await browser.close();
console.log(JSON.stringify({result,errors},null,2));
const bad=result.checks.filter(x=>x[1]==='FAIL');
if(bad.length||errors.some(x=>!x.includes('Failed to load resource')&&!x.includes('favicon')))process.exitCode=2;